ACEDS_PMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("patients.urls")),

    path("admin/", admin.site.urls),
]

patients/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from sqlalchemy.dialects.mssql.information_schema import views

from patients.views import home, register, register_create, custom_login, patient_dashboard, admin_dashboard, \
    create_rendezvous, rendezvous_update, rendezvous_delete

urlpatterns = [
    path('', home, name='home'),
    path('patient/register/', register, name='register'),
    path('patient/register/create', register_create, name='register_create'),
    path('patient/dashboard/', patient_dashboard, name='patient_dashboard'),
    path('patient/create-rendezvous/', create_rendezvous, name='create_rendezvous'),
    path('patient/update-rendezvous/<int:pk>/', rendezvous_update, name='update_rendezvous'),
    path('patient/delete-rendezvous/<int:pk>/', rendezvous_delete, name='delete_rendezvous'),
    path('admin/dashboard/', admin_dashboard, name='admin_dashboard'),
    path('login/', custom_login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

patients/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
HDFS_URL = "http://167.99.86.23:9870"
class SystemUser(AbstractUser):
    USER_TYPES=(
        ('ADMIN','Admin'),
        ('DOCTOR','Doctor'),
        ('PATIENT','Patient'),
    )
    user_type=models.CharField(max_length=20,choices=USER_TYPES,default='ADMIN')
    national_id=models.CharField(max_length=20,unique=True)
    phone_number=models.CharField(max_length=20,unique=True)
    date_of_birth=models.DateField(null=True)


class Department(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    department_contact = models.CharField(max_length=100, null=True, blank=True)
    doctors = models.ManyToManyField(SystemUser, related_name='doctors', blank=True,limit_choices_to={'user_type':'DOCTOR'})

    def __str__(self):
        return self.name

class Rendezvous(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('APPROVED', 'Approved'),
        ('REJECTED', 'Rejected'),
    ]



    URGENCY_CHOICES = [
        ('ROUTINE', 'Routine'),
        ('URGENT', 'Urgent'),
        ('EMERGENCY', 'Emergency'),
    ]

    patient = models.ForeignKey(
        SystemUser,
        on_delete=models.CASCADE,
        related_name='rendezvous_requests',
        limit_choices_to={'user_type': 'PATIENT'}
    )
    department = models.ForeignKey('Department', on_delete=models.CASCADE, related_name='rendezvous_requests')
    doctor = models.ForeignKey(
        SystemUser,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='assigned_rendezvous',
        limit_choices_to={'user_type': 'DOCTOR'}
    )
    request_date = models.DateTimeField(auto_now_add=True)
    preferred_date = models.DateField(null=True, blank=True)
    symptoms = models.TextField(null=True, blank=True)
    urgency_level = models.CharField(max_length=10, choices=URGENCY_CHOICES, default='ROUTINE')
    contact_number = models.CharField(max_length=15, null=True, blank=True)
    insurance_provider = models.CharField(max_length=100, null=True, blank=True)
    additional_notes = models.TextField(null=True, blank=True)
    assigned_date = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='PENDING')
    reply = models.TextField(null=True, blank=True)
    file_path = models.CharField(max_length=255, blank=True, null=True)

    def get_download_url(self):
        return f"{HDFS_URL}/webhdfs/v1{self.file_path}?op=OPEN"

patients/forms.py
from django import forms

from patients.models import SystemUser, Rendezvous


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = SystemUser
        fields = ['first_name', 'last_name', 'date_of_birth', 'national_id', 'phone_number', 'email', 'password']
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'date_of_birth': 'Date of Birth',
            'national_id': 'National ID',
            'phone_number': 'Phone Number',
            'email': 'Email',
            'password': 'Password'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={
                'type': 'date',  # HTML5 native datepicker
                'class': 'form-control',  # Add Bootstrap styling
                'placeholder': 'YYYY-MM-DD',  # Optional placeholder
                'autocomplete': 'off',  # Prevent browser autofill
            }),
            'national_id': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class RendezvousForm(forms.ModelForm):
    class Meta:
        model = Rendezvous
        fields = ['department', 'preferred_date',  'symptoms', 'urgency_level',
                  'contact_number', 'additional_notes','insurance_provider','file_path']
        labels = {
            'department': 'Select Department',
            'preferred_date': 'Preferred Appointment Date',
            'preferred_time_slot': 'Preferred Time Slot',
            'symptoms': 'Describe Your Symptoms',
            'urgency_level': 'Urgency Level',
            'contact_number': 'Contact Number',
            'additional_notes': 'Additional Notes',
            'file_path': 'Upload File',
        }
        widgets = {
            'department': forms.Select(attrs={'class': 'form-control'}),
            'preferred_date': forms.DateInput(attrs={
                'type': 'date',  # HTML5 native datepicker
                'class': 'form-control',  # Add Bootstrap styling
                'placeholder': 'YYYY-MM-DD',  # Optional placeholder
                'autocomplete': 'off',  # Prevent browser autofill
            }),
            'symptoms': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'urgency_level': forms.Select(attrs={'class': 'form-control'}),
            'contact_number': forms.TextInput(attrs={'class': 'form-control'}),
            'insurance_provider': forms.TextInput(attrs={'class': 'form-control'}),
            'additional_notes': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'file_path': forms.ClearableFileInput(attrs={'class': 'form-control'}),

        }

patients/views.py
import json
# from lib2to3.fixes.fix_input import context
# from kafka import KafkaProducer

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.db import connection
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from docutils.nodes import pending
from hdfs import InsecureClient
from kafka import KafkaProducer

from patients.forms import UserRegistrationForm, RendezvousForm
from patients.models import Rendezvous

# Kafka producer configuration
KAFKA_TOPIC = 'rendezvous_requests'
KAFKA_BOOTSTRAP_SERVERS = 'localhost:9092'

HDFS_URL = "http://167.99.86.23:9870"
HDFS_PATH = "/appointments"

producer = KafkaProducer(
    bootstrap_servers=KAFKA_BOOTSTRAP_SERVERS,
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
)

# Create your views here.
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
def home(request):
    return render(request, "index.html")


def register(request):
    form = UserRegistrationForm()
    context = {'form': form}
    return render(request, "register.html", context)


def custom_login(request):
    if request.method == 'POST':
        username = request.POST.get('phone')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.user_type == 'PATIENT':
                return redirect('patient_dashboard')
            if user.user_type == 'ADMIN':
                return redirect('admin_dashboard')

        else:
            messages.error(request, "Invalid username or password.")
            return render(request, "login.html")
    return render(request, "login.html")


@login_required
def patient_dashboard(request):
    if request.user.user_type != 'PATIENT':
        messages.error(request, "You are not authorized to view this page.")
        return redirect('login')
    form = RendezvousForm()

    rendezvous_requests = Rendezvous.objects.filter(patient=request.user).order_by('-request_date')
    ctx = {
        'form': form,
        'rendezvous_requests': rendezvous_requests,
    }
    return render(request, "patient_dashboard.html", ctx)


def create_rendezvous(request):
    if request.method == 'POST':
        form = RendezvousForm(request.POST, request.FILES)
        try:
            if form.is_valid():
                # rendezvous = form.save(commit=False)
                # rendezvous.patient = request.user
                # rendezvous.save()
                client=InsecureClient(HDFS_URL,user='dr.who')
                file_path=None
                if 'file_path' in request.FILES:
                    file=request.FILES['file_path']
                    file_path=f'{HDFS_PATH}/{file.name}'
                    with client.write(f'{HDFS_PATH}/{file.name}', overwrite=True) as writer:
                        for chunk in file.chunks():
                            writer.write(chunk)
                # print file name





                rendezvous_data = {
                    'patient_id': request.user.id,  # Serialize patient ID
                    'department_id': form.cleaned_data['department'].id,  # Serialize department ID
                    'preferred_date': form.cleaned_data['preferred_date'].isoformat(),  # Serialize date
                    'urgency_level': form.cleaned_data['urgency_level'],
                    'symptoms': form.cleaned_data['symptoms'],
                    'contact_number': form.cleaned_data['contact_number'],
                    'insurance_provider': form.cleaned_data['insurance_provider'],
                    'additional_notes': form.cleaned_data['additional_notes'],
                    'file_path': file_path
                }

                # Send data to Kafka
                producer.send(KAFKA_TOPIC, rendezvous_data)
                producer.flush()  # Ensure the message is sen
                messages.success(request, "Rendezvous request created successfully.")

                if is_ajax(request):
                    return JsonResponse({"message": "Rendezvous request created successfully."})
                return redirect('patient_dashboard')



        except Exception as e:
            print(f"Error creating rendezvous: {e}")
            messages.error(request, "An error occurred while creating the rendezvous request.")
            return redirect('patient_dashboard')

    else:
        form=RendezvousForm()
    ctx={'form':form}
    if is_ajax(request):
        html=render_to_string('rendezvous_form.html',ctx,request=request)
        return JsonResponse({'html':html})
    return render(request,'rendezvous_form.html',ctx)

def rendezvous_update(request, pk):
    rendezvous = get_object_or_404(Rendezvous, pk=pk)
    if request.method == 'POST':
        form = RendezvousForm(request.POST, instance=rendezvous)
        if form.is_valid():
            form.save()
            if is_ajax(request):
                return JsonResponse({"message": "Author updated successfully"})
            return redirect('patient_dashboard')
    else:
        form = RendezvousForm(instance=rendezvous)
    ctx = {'form': form}
    if is_ajax(request):
        html = render_to_string('rendezvous_form.html', ctx, request=request)
        return JsonResponse({'html': html})
    return render(request, 'rendezvous_form.html', ctx)

def rendezvous_delete(request, pk):
    rendezvous = get_object_or_404(Rendezvous, pk=pk)
    if request.method == 'GET':
        rendezvous.delete()
        return redirect('patient_dashboard')

@login_required
def admin_dashboard(request):
    if request.user.user_type != 'ADMIN':
        messages.error(request, "You are not authorized to view this page.")
        return redirect('login')

        # SQL query to count patients above and below 18 using TIMESTAMPDIFF
    try:
        query = """
                    SELECT 
                        SUM(CASE WHEN TIMESTAMPDIFF(YEAR, date_of_birth, CURDATE()) >= 18 THEN 1 ELSE 0 END) AS above_18,
                        SUM(CASE WHEN TIMESTAMPDIFF(YEAR, date_of_birth, CURDATE()) < 18 THEN 1 ELSE 0 END) AS below_18
                    FROM patients_systemuser
                    WHERE user_type = 'PATIENT';
                """

        with connection.cursor() as cursor:
            cursor.execute(query)
            result = cursor.fetchone()

        # Extract counts
        above_18_count = result[0] or 0
        below_18_count = result[1] or 0

        total_pending_rdv=Rendezvous.objects.filter(status='PENDING').count()
        total_approved_rdv=Rendezvous.objects.filter(status='APPROVED').count()

        pending_rdvs=Rendezvous.objects.filter(status="PENDING").order_by('-request_date')[:10]

        for rdv in pending_rdvs:
            if rdv.file_path:
                rdv.download_file=f"{HDFS_URL}/webhdfs/v1{rdv.file_path}?op=OPEN"
        #         print file path
                print(rdv.download_file)



        # Pass the counts to the template
        context = {
            'above_18_count': above_18_count,
            'below_18_count': below_18_count,
            'total_pending_rdv':total_pending_rdv,
            'total_approved_rdv':total_approved_rdv,
            'pending_rdvs':pending_rdvs
        }
    except Exception as e:
        print(f"Error fetching data: {e}")
        messages.error(request, "An error occurred while fetching patient data.")
        context = {
            'above_18_count': 0,
            'below_18_count': 0,
        }

    return render(request, "admin_dashboard.html", context)


def register_create(request):
    form = UserRegistrationForm(request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        user.user_type = 'PATIENT'
        user.password = make_password(form.cleaned_data['password'])
        user.username = form.cleaned_data['phone_number']
        user.save()
        messages.success(request, "Registration successful! You can now log in.")
        return redirect('register')
    else:
        messages.error(request, "Registration failed. Please try again.")
        return render(request, "register.html", {'form': form})

patients/templates/patient_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        .text-justify {
            text-align: justify;
        }
    </style>
</head>
<body class="min-vh-100">

<div class="container min-vh-100">
    <div class="d-flex min-vh-100 flex-column justify-content-start">
        <nav class="navbar mb-2 navbar-expand-lg  bg-opacity-10">
            <div class="container">
                <a class="navbar-brand fs-2 fw-bolder" href="#">PMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav fw-semibold mx-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="index.html">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Requests</a>
                        </li>

                    </ul>
                    <div class="d-flex align-items-center gap-2">
                        {#                        add logout button#}
                        <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
                        <span class=" ">Welcome</span>
                        <span class="d-flex rounded-circle align-items-center  bg-success-subtle justify-content-center"
                              style="height: 50px;width: 50px;">
                            Ad
                        </span>

                    </div>
                </div>
            </div>
        </nav>
        <div class="row mt-4">

            <div class="d-flex justify-content-between align-items-center justify-content-end mb-1">
                <h2>My Appointments</h2>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                        data-bs-target="#addRendezvousModal"
                        onclick="openRendezVousModal('{% url 'create_rendezvous' %}')">
                    Schedule an appointment
                </button>
            </div>
            <table class="table table-striped mt-4">
                <thead class="table-dark">
                <tr>
                    <th>#</th>
                    <th>Department</th>
                    <th>Symptoms</th>
                    <th>Urgency Level</th>
                    <th>Contact Number</th>
                    <th>Preferred Date</th>
                    <th>Request Date</th>
                    <th>Assigned Date</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for rendezvous in rendezvous_requests %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ rendezvous.department.name }}</td>
                        <td>{{ rendezvous.symptoms }}</td>
                        <td>{{ rendezvous.get_urgency_level_display }}</td>
                        <td>{{ rendezvous.contact_number }}</td>
                        <td>{{ rendezvous.preferred_date|date:"Y-m-d" }}</td>
                        <td>{{ rendezvous.request_date|date:"Y-m-d H:i" }}</td>
                        <td>{{ rendezvous.assigned_date|default:"N/A" }}</td>
                        <td>
                            {% if rendezvous.status == 'PENDING' %}
                                <span class="badge bg-warning text-dark">{{ rendezvous.get_status_display }}</span>
                            {% elif rendezvous.status == 'APPROVED' %}
                                <span class="badge bg-success">{{ rendezvous.get_status_display }}</span>
                            {% elif rendezvous.status == 'REJECTED' %}
                                <span class="badge bg-danger">{{ rendezvous.get_status_display }}</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if rendezvous.status == 'PENDING' %}



                                <button class="btn btn-sm btn-warning px-4 rounded-pill" data-bs-toggle="modal"
                                        data-bs-target="#addRendezvousModal"
                                        onclick="openRendezVousModal('{% url 'update_rendezvous' rendezvous.pk %}')">Update
                                </button>
                                 <a class="btn btn-sm btn-danger px-4 rounded-pill"  href="{% url 'delete_rendezvous' rendezvous.pk %}"
                                      >Delete
                                </a>

                                {#                                <button class="btn btn-sm btn-danger px-4 rounded-pill" data-bs-toggle="modal"#}
                                {#                                        data-bs-target="#deleteModal"#}
                                {#                                        onclick="openDeleteModal('{% url 'rendezvous_delete' book.pk %}', '{{ book.title }}')">#}
                                {#                                    Delete#}
                                {#                                </button>#}

                            {% else %}
                                <span class="text-muted">No actions available</span>
                            {% endif %}
                        </td>
                        {#                        <td>#}
                        {#                            {% if rendezvous.file_upload %}#}
                        {#                                <a href="{{ rendezvous.file_upload.url }}" target="_blank">View File</a>#}
                        {#                            {% else %}#}
                        {#                                No file uploaded#}
                        {#                            {% endif %}#}
                        {#                        </td>#}
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6" class="text-center">No rendezvous requests found.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {#    rendez vous model #}
        <div class="modal fade" id="addRendezvousModal" tabindex="-1" aria-labelledby="addRendezvousModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="addRendezvousModalLabel">Add New Rendezvous</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="modal-body-content">
                        <!-- Form -->
                        {#                        <form method="post" action="{% url 'create_rendezvous' %}" enctype="multipart/form-data">#}
                        {#                            {% csrf_token %}#}
                        {#                            <div class="mb-3">#}
                        {#                                <label for="id_department" class="form-label">Department</label>#}
                        {#                                {{ form.department }}#}
                        {#                            </div>#}
                        {#                            <div class="mb-3">#}
                        {#                                <label for="id_urgency_level" class="form-label">Symptoms</label>#}
                        {#                                {{ form.symptoms }}#}
                        {#                            </div>#}
                        {##}
                        {#                            <div class="mb-3">#}
                        {#                                <label for="id_preferred_date" class="form-label">Preferred Date</label>#}
                        {#                                {{ form.preferred_date }}#}
                        {#                            </div>#}
                        {#                            <div class="mb-3">#}
                        {#                                <label for="id_urgency_level" class="form-label">Urgency Level</label>#}
                        {#                                {{ form.urgency_level }}#}
                        {#                            </div>#}
                        {#                            <div class="mb-3">#}
                        {#                                <label for="id_urgency_level" class="form-label">Additional Notes</label>#}
                        {#                                {{ form.additional_notes }}#}
                        {#                            </div>#}
                        {#                        <div class="mb-3">#}
                        {#                            <label for="id_file_upload" class="form-label">Upload File</label>#}
                        {#                            {{ form.file_upload }}#}
                        {#                        </div>#}
                        {#                            <button type="submit" class="btn btn-primary">Submit</button>#}
                        {#                        </form>#}
                    </div>
                </div>
            </div>
        </div>

        <footer>
            <div class="bg-success fixed-bottom bg-opacity-10 d-flex justify-content-center w-100">
                <span class="text-black  text-center text-sm py-3">Patient Management System</span>
            </div>
        </footer>
    </div>
</div>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
    function openRendezVousModal(url) {
        //disable the submit button
        fetch(url, {
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            }
        })
            .then(response => response.json())
            .then(data => {

                document.getElementById('modal-body-content').innerHTML = data.html;
                document.querySelector('#addRendezvousModal form').addEventListener('submit', function (event) {

                    event.preventDefault();
                    submitRendezVousForm(this);
                });
            });
    }

    function submitRendezVousForm(form) {
        document.querySelector('#addRendezvousModal form button[type="submit"]').disabled = true;
        //change the button text
        document.querySelector('#addRendezvousModal form button[type="submit"]').textContent = 'Processing...';

        const url = form.action;
        const formData = new FormData(form);
        fetch(url, {
            method: 'POST',
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            },
            body: formData
        })
            .then(response => response.json())
            .then(data => {
                if (data.message) {
                    location.reload(); // Reload the page to see the changes
                } else {
                    document.getElementById('modal-body-content').innerHTML = data.html;
                    document.querySelector('#addRendezvousModal form').addEventListener('submit', function (event) {
                        event.preventDefault();
                        submitRendezVousForm(this);
                    });
                }
            });
    }


</script>
</body>
</html>

patients/templates/rendezvous_form.html
<form method="post" action="{% if form.instance.pk %}{% url 'update_rendezvous' form.instance.pk %}{% else %}{% url 'create_rendezvous' %} {% endif %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_department" class="form-label">Department</label>
        {{ form.department }}
    </div>
    <div class="mb-3">
        <label for="id_urgency_level" class="form-label">Symptoms</label>
        {{ form.symptoms }}
    </div>

    <div class="mb-3">
        <label for="id_preferred_date" class="form-label">Preferred Date</label>
        {{ form.preferred_date }}
    </div>
     <div class="mb-3">
        <label for="id_preferred_date" class="form-label">Your Insurance</label>
        {{ form.insurance_provider }}
    </div>
    <div class="mb-3">
        <label for="id_preferred_date" class="form-label">Contact Number</label>
        {{ form.contact_number }}
    </div>
    <div class="mb-3">
        <label for="id_urgency_level" class="form-label">Urgency Level</label>
        {{ form.urgency_level }}
    </div>
    <div class="mb-3">
        <label for="id_urgency_level" class="form-label">Additional Notes</label>
        {{ form.additional_notes }}
    </div>
    <div class="mb-3">
        <label for="id_file_path" class="form-label">Upload File</label>
        {{ form.file_path }}
    </div>
    {#                        <div class="mb-3">#}
    {#                            <label for="id_file_upload" class="form-label">Upload File</label>#}
    {#                            {{ form.file_upload }}#}
    {#                        </div>#}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>